name: Example SSH Action Usage

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Execute deployment script
      uses: ./
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: '22'  # Optional, defaults to 22
        script: |
          echo "Deployment started at $(date)"
          whoami
          pwd
          uptime
          echo "Deployment completed!"
    
    - name: Execute maintenance script on custom port
      uses: ./
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: '2222'
        script: |
          #!/bin/bash
          echo "Running system maintenance..."
          df -h
          free -m
          echo "Maintenance completed!" 